version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=doctors_appointment_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

volumes:
  postgres_data:
